### ISSUE TITLE
a new text for source file 

### ISSUE THREAD

**Issue by HUANG0421** [readchina/ReadingData#176]
I've found a new text for P0041, named "高考，废除与恢复". 
And here is a online link: https://www.jianshu.com/p/a34968175b9d?utm_campaign=maleskine&utm_content=note&utm_medium=pc_all_hots&utm_source=recommendation
Please check if it fits this person. :)
@duncdrum @inamoto4 @LenaHenningsen

**Comment by HUANG0421** [comment]
And another text:
For P0046, named "在万县旁观“夺权”与“镇反”", online link: http://blog.sina.com.cn/s/blog_d761eefc0102wjym.html

**Comment by LenaHenningsen** [comment]
The first text definetely seems fitting @inamoto4  should we also use that to collect reading data as the lady mentions a number of her readings? 
(Will check the second text now and come back later)

**Comment by LenaHenningsen** [comment]
And the second one also seems a hit - I don't see readings mentioned. In case there are some please include.
Thanks

**Comment by inamoto4** [comment]
Can this be closed?

**Comment by duncdrum** [comment]
I would close it once the new sources are in our database. Keep it open as a reminder until then.

**Comment by duncdrum** [comment]
@HUANG0421 please make close this ticket once the sources have been added
