### ISSUE TITLE
Missing sources in person file

### ISSUE THREAD

**Issue by inamoto4** [readchina/ReadingData#205]
Please add the missing sources. If only a name is mentioned, still add the source.

@HUANG0421 
-   [x] P0054. What does "zugong tongxun 1980" mean?
-   [x] P0099
-   [x] P0107

@mira-gruenwald 
-   [x] P0166
-   [x] P0168
-   [x] P0169
-   [x] P0171
-   [ ] P0172
-   [x] P0173
-   [x] P0175

see #201

**Comment by duncdrum** [comment]
fixed by 0990d52c1ab06e81f334f7e52ddb54f36679c9c1
