### ISSUE TITLE
P0172 Zhenzhen

### ISSUE THREAD

**Issue by mira-gruenwald** [readchina/ReadingData#213]
I just wanted to check the source for Zhenzhen ( see #205 ) and found the following commentary on this person in the "old" text file:
"Note that this work is also referred to in Open Love Letters by Zhenzhen"

Is Zhenzhen a character in this book? Should "Open Love Letters" then be the source for Zhenzhen?

Thank you!

**Comment by LenaHenningsen** [comment]
Thanks for asking. Please ignore this comment - we will add this stuff when we really start to work on the fictional sources.
