### ISSUE TITLE
False quotes

### ISSUE THREAD

**Issue by inamoto4** [readchina/ReadingData#217]
How exactly do we deal with false quotes in our life writing sources? In my case I have encountered a wrongly ascribed quote (the author of 水经注 is 郦道元 and not 盛弘之), which also lacked a character (compared to the version on baidu).

**Comment by duncdrum** [comment]
I'd say since we are recording people's claims, the veracity of the attribution is secondary. The fascinating thing about quotes is that if enough ppl believe that Bones said: "He is dead, Jim", it hardly matters if he didn't. I vote to keep as is, but mention the discrepancy in the comments.
