### ISSUE TITLE
Where are we at?

### ISSUE THREAD

**Issue by duncdrum** [readchina/ReadingData#254]
Could someone indicate which letters have been completely transferred?

@damianodamiani I guess you discussed this at the meeting. we can use the second project board to keep better track of where we are, once we know which letters have been done and which haven't

**Comment by damianodamiani** [comment]
hey @duncdrum, yup, we're assigning letters on the meetings (or via email if the meeting is postponed). We figured that in around 4-5 weeks the transfer should be fully completed (fingers crossed!)

**Comment by duncdrum** [comment]
Do you have to do a once over regarding every letter, or are some already complete?

**Comment by damianodamiani** [comment]
overdue, all arranged
