### ISSUE TITLE
Michelet, Histoire de France - Publication

### ISSUE THREAD

**Issue by mira-gruenwald** [readchina/ReadingData#269]
I'm having difficulties in finding an edition of Jules Michelets _Histoire de France_.

- [ ] PS00483

I searched on Worldcat and nlc..are there other catalogues where we could find an edition? Thank you !

see #267

**Comment by duncdrum** [comment]
if this came straight from the french I assume this would be the Saint-Clair  edition in 18 vol from the 1960s? Or did it come via translation into another language [en](https://archive.org/details/historyfrancetr00michgoog) in just 2 vol. ?
