### ISSUE TITLE
Difference between AT01 and AT05

### ISSUE THREAD

**Issue by damianodamiani** [readchina/ReadingData#282]
Dear all, I'm finding myself more and more uncertain when it comes to the exact difference between 'read' and 'mention.' We talked about it already with @LenaHenningsen but thought we should discuss it collectively. 

Look at the following two example sentences, each from another source but both about W.L. Shirer's _Rise and Fall of the Third Reich_:

> "在那些年读过的书籍中, 给我留下 最深印象的是威廉·夏伊勒的《第三帝国的兴亡》和《赫鲁晓夫回忆 录》"

> "我们曾狂热地读现有的书，如《第三帝国的兴亡》等" 

In both cases, the author clearly indicates having _read_ the book. Yet at the same time, they _mention_ the book among others. I stumbled upon other similar cases before and would then just arbitrarily assign AT01 or AT05 based on how I understand the text. But that's not perfect hence the difference between 'read' and 'mention' is oftentimes pretty small - when not directly created by the interpreter (i.e. us). What do you think about this? How do you proceed in similar situations?

I'm wondering whether we should add to the helper some kind of glosary in which we clearly define what each act type _exactly_ means? (Another shaky triangle for me is AT15, AT16 and AT22...)

**Comment by duncdrum** [comment]
IMV mentioning is the least restrictive category, and should only be used when reading (or any other more specific act) can not be ascertained from the source material. 

So in both your examples the act is clearly to read (读), the mentioning that you seem to have in mind is implied in the source relation of the recorded act, and not a separate act to be recorded. 

Any clarification for the use of terms should go into the data dictionary.
