### ISSUE TITLE
missing english titles in Secondary Source

### ISSUE THREAD

**Issue by mira-gruenwald** [readchina/ReadingData#296]
Please translate the following titles:

SS00139
--
SS00140
SS00141
SS00142
SS00143
SS00144
SS00145
SS00146
SS00147
SS00148
SS00150
SS00238
SS00239
SS00240
SS00241
SS00242
SS00243
SS00244
SS00245
SS00246
SS00247

**Comment by duncdrum** [comment]
@mira-gruenwald can you check #218 and create one issues in here that tracks all of these together, thx.

**Comment by damianodamiani** [comment]
I will also recheck all the translations in this CSV later this week so that we have a coherent style.

**Comment by duncdrum** [comment]
@damianodamiani pls check travis, once the checks pass i think this is good to go as a pull request
