### ISSUE TITLE
non-existing ID pointers

### ISSUE THREAD

**Issue by duncdrum** [readchina/ReadingData#300]
The following  IDs are referenced in a table, but don't exist in their respective main tables:
-  Act:
   -   P0144
   -   P0083
-  PrimarySource:
   -  P0102
- SocialRelation:
  -  P0035

**Comment by mira-gruenwald** [comment]
@duncdrum 
Sometimes Travis is listing "unknown" as a bad ID pointer, especially when it's about Place-IDs. Would it make sense to add an unknown Place like PL0999 and add this ID to our files where we don't know the exact place?

**Comment by duncdrum** [comment]
yes places are primary entities, so there should be a `PL0999` id for unknown places which is referenced from other tables.
