### ISSUE TITLE
what genre do we assign to Sima Qian's 史記?

### ISSUE THREAD

**Issue by damianodamiani** [readchina/ReadingData#321]
I don't fully understand the difference between G36 Historical nonfiction and G41 History either, especially becuase G36 seems not to be a clearly defined thing at the LibOfCongress site

**Comment by duncdrum** [comment]
i'd say just follow the [Library of Congress](http://id.loc.gov/authorities/names/n79081033.html) catalogue. 24 standard histories are their own genre, which makes sense imv

**Comment by damianodamiani** [comment]
OK, going for G41 History. We can look into the exact genre borderlines once the transfer is ready as I have many more objections.

**Comment by duncdrum** [comment]
what i meant was stick either with [LoC](http://id.loc.gov/authorities/genreForms/gf2014026045.html) or [wikiData](https://www.wikidata.org/wiki/Q175077), aka add a new genre
