### ISSUE TITLE
Commas in parallel names?

### ISSUE THREAD

**Issue by HUANG0421** [readchina/ReadingData#335]
Hello :)
How should we deal with the commas in some parallel names? Such as in this sentence: 

He was an actor who fell for **Chekhov, Ostrovsky, Cao Yu and Xia Yan.** Even after experiencing cruel torture he still kept his hope for his own people and the whole humankind.
--
This sentence is in Act Discussion, I've read the old issues but didn't find an answer, should I use ';' instead of ','? 
Wish you all a sweet Christmas Eve! :)

**Comment by duncdrum** [comment]
I would quote escape the whole field `"He was an actor who fell for Chekhov, Ostrovsky, Cao Yu and Xia Yan. Even after experiencing cruel torture he still kept his hope for his own people and the whole humankind."`
