### ISSUE TITLE
Numbers attributed?

### ISSUE THREAD

**Issue by LenaHenningsen** [readchina/ReadingData#348]
Dear all, have you attributed numbers for reading acts persons etc. to some of you, I am trying to finish Sasha Gong and don't want to mess with your system.

**Comment by LenaHenningsen** [comment]
Thanks a lot – I tried to commit my changes tot he branch but somehow something’s wrong; will get back to you in the afternoon, but have to go now…

Lena

 

Von: Duncan Paterson <notifications@github.com>
Antworten an: readchina/ReadingData <reply@reply.github.com>
Datum: Donnerstag, 31. Januar 2019 um 12:06
An: readchina/ReadingData <ReadingData@noreply.github.com>
Cc: LenaHenningsen <Lena.Henningsen@sinologie.uni-freiburg.de>, Author <author@noreply.github.com>
Betreff: Re: [readchina/ReadingData] Numbers attributed? (#348)

 

You can check the initial Letters of ongoing transfers here, no one is currently working on S so provided that your local files are up to date, go ahead. I m sure I m speaking for all of us that we are happy to rebase, to take your input into account (should rebasing be necessary at all).

**Comment by duncdrum** [comment]
yes you are working in the wrong repo. You are editing csv files in duncdrum/readchina (the database app) but you want to work in readchina/ReadingData ie here

**Comment by LenaHenningsen** [comment]
Uaaaaa. Thanks for pointing out… so I open a new one and try to copy-paste the stuff I guess

 

Von: Duncan Paterson <notifications@github.com>
Antworten an: readchina/ReadingData <reply@reply.github.com>
Datum: Donnerstag, 31. Januar 2019 um 13:19
An: readchina/ReadingData <ReadingData@noreply.github.com>
Cc: LenaHenningsen <Lena.Henningsen@sinologie.uni-freiburg.de>, Author <author@noreply.github.com>
Betreff: Re: [readchina/ReadingData] Numbers attributed? (#348)

 

yes you are working in the wrong repo. You are editing csv files in duncdrum/readchina (the database app) but you want to work in readchina/ReadingData ie here

**Comment by LenaHenningsen** [comment]
Very stupid question: how do I get to the correct one in github desktop

 

Von: Duncan Paterson <notifications@github.com>
Antworten an: readchina/ReadingData <reply@reply.github.com>
Datum: Donnerstag, 31. Januar 2019 um 13:19
An: readchina/ReadingData <ReadingData@noreply.github.com>
Cc: LenaHenningsen <Lena.Henningsen@sinologie.uni-freiburg.de>, Author <author@noreply.github.com>
Betreff: Re: [readchina/ReadingData] Numbers attributed? (#348)

 

yes you are working in the wrong repo. You are editing csv files in duncdrum/readchina (the database app) but you want to work in readchina/ReadingData ie here

**Comment by duncdrum** [comment]
Check the wiki there is a [screenshot](
https://camo.githubusercontent.com/eebc5bb0787adfde588ea10c3383814e0e19b07f/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f732f6c6176667371776f65796c723469742f47482d4465736b746f70312e706e673f646c3d30) you want to bbe in readingData not readchina

**Comment by LenaHenningsen** [comment]
Thanks – I hope that I worked it out right this time; 

By the way the primary sources files in both repos contain titles that the respective other ones do not contain. 612, for example is only in one; while 586 (and the ones before these two) in the other. Or maybe I misread something…

… will do another try tomorrow in order to get into the routine. So sorry for opening a branch just for these small things.

Lena

 

Von: Duncan Paterson <notifications@github.com>
Antworten an: readchina/ReadingData <reply@reply.github.com>
Datum: Donnerstag, 31. Januar 2019 um 14:17
An: readchina/ReadingData <ReadingData@noreply.github.com>
Cc: LenaHenningsen <Lena.Henningsen@sinologie.uni-freiburg.de>, Author <author@noreply.github.com>
Betreff: Re: [readchina/ReadingData] Numbers attributed? (#348)

 

Check the wiki there is a screenshot you want to bbe in readingData not readchina

**Comment by duncdrum** [comment]
opening a branch is the way to do this, try to get travis to be green with just these changes tomorrow. 
The PS ids here are the right ones, they'll get updated automatically when i next merge to master in readchina, nothing to worry about.
