### ISSUE TITLE
Paul Gauguin

### ISSUE THREAD

**Issue by LenaHenningsen** [readchina/ReadingData#392]
In the spreadsheet we did in the afternoon there is P0677, referring to Lang Jinguang, whereas in the characters it says 

高更

i.e. reference to Gaugin... (P0670) Who is it?? 
Likewise, the next refers to P0637, but the characters refer to 

de Secondat 634
--
But this one appears a second time (with correct Person ID a couple of rows below)

Further down then there is Khrushchev's P ID, but the Chinese character qian... for the surname.

Then two rows below another surname qian, but person ID for Zhou Libo 

P0249
--

**Comment by LenaHenningsen** [comment]
Then the next is Sholokhov P0439 who appears for P0452 Su Shi (that's a nice one!!)

Then another qian that leads to Dostojevski?? P0233

And related - how can there be 3 text by Anne Frank??

Then we have Zhuang Zhou who appears with surname Xu? 

And Qu Qiubai with surname Meng??

**Comment by duncdrum** [comment]
The Lookup function did return the wrong results, since the IDs in the person table weren't sorted. I ve switched to the VLOOKUP functin and sorted the table for good measure. Results are now correct
